question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, "
             "you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_2 = [{"category": "History", "type": "boolean", "difficulty": "easy",
                    "question": "The Cold War ended with Joseph Stalin&#039;s death.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Geography", "type": "boolean", "difficulty": "easy",
                    "question": "San Marino is the only country completely surrounded by another country.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Music", "type": "boolean",
                    "difficulty": "medium",
                    "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                    "question": "The Japanese Shinkansen beat the French TGV&#039;s "
                                "speed record for fastest electric rail train.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science & Nature", "type": "boolean",
                    "difficulty": "medium",
                    "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Film", "type": "boolean",
                    "difficulty": "easy",
                    "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot"
                                ";Inception&quot;.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Video Games", "type": "boolean",
                    "difficulty": "easy", "question": "Luigi is taller than Mario?",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Gadgets", "type": "boolean",
                    "difficulty": "easy",
                    "question": "The communication protocol NFC stands for Near-Field Control.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Geography", "type": "boolean", "difficulty": "medium",
                    "question": "Vietnam is the only country in the world that starts with V. ",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Video Games", "type": "boolean",
                    "difficulty": "medium",
                    "question": "In &quot;Team Fortress 2&quot;, "
                                "the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Board Games", "type": "boolean",
                    "difficulty": "easy",
                    "question": "The card game &quot;Munchkin&quot; "
                                "won the 2001 Origins Award for Best Traditional Card Game.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "General Knowledge", "type": "boolean",
                    "difficulty": "medium",
                    "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Politics", "type": "boolean", "difficulty": "medium",
                    "question": "During the 2016 United States "
                                "presidential election, the State of California "
                                "possessed the most electoral votes, having 55.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean",
                    "difficulty": "easy",
                    "question": "The Windows 7 operating system has six main editions.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Entertainment: Video Games", "type": "boolean",
                    "difficulty": "easy",
                    "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Video Games", "type": "boolean",
                    "difficulty": "easy",
                    "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Entertainment: Music", "type": "boolean",
                    "difficulty": "medium",
                    "question": "3 members of 2 Live Crew were arrested for "
                                "playing songs from their album, As Nasty As They Wanna Be, live.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Entertainment: Board Games", "type": "boolean",
                    "difficulty": "easy",
                    "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Music", "type": "boolean",
                    "difficulty": "easy", "question": "Daft Punk originated in France.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "History", "type": "boolean", "difficulty": "hard",
                    "question": "The USS Missouri (BB-63) last served in the Korean War.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Television", "type": "boolean",
                    "difficulty": "medium",
                    "question": "Klingons respect their disabled comrades, "
                                "and those who are old, injuried, and helpless.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Television", "type": "boolean",
                    "difficulty": "easy",
                    "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                    "question": "A wyvern is the same as a dragon.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Video Games", "type": "boolean",
                    "difficulty": "easy",
                    "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Entertainment: Music", "type": "boolean",
                    "difficulty": "easy",
                    "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Entertainment: Cartoon & Animations",
                    "type": "boolean", "difficulty": "medium",
                    "question": "Night on Bald Mountain was one of the musical pieces"
                                " featured in Disney&#039;s 1940&#039;s film Fantasia.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "General Knowledge", "type": "boolean",
                    "difficulty": "easy",
                    "question": "Slovakia is a member of European Union-",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Art", "type": "boolean", "difficulty": "hard",
                    "question": "The Statue of Liberty&#039;s official "
                                "name is &ldquo;Liberty Enlightening the World&rdquo;.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Sports", "type": "boolean", "difficulty": "easy",
                    "question": "There are a total of 20 races in Formula One 2016 season.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
                    "difficulty": "hard",
                    "question": "The protagonist&#039;s names in &#039;Who&#039;s "
                                "Afraid of Virginia Woolf&#039;, George and Martha, were derived from George "
                                "Washington and his wife.",
                    "correct_answer": "True", "incorrect_answers": ["False"]}]
